---
kind: Service
apiVersion: v1
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  ports:
    -  port: 21
       targetPort: 21
       name: ftps-main
    -  port: 2100
       targetPort: 2100
       name: ftps-port-one
    -  port: 2101
       targetPort: 2101
       name: ftps-port-zero
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - imagePullPolicy: Never
        image: local-ftps
        name: ftps
        ports:
        - containerPort: 21
          name: "ftps-main"
        - containerPort: 2100
          name: "ftps-port-zero"
        - containerPort: 2101
          name: "ftps-port-one"
        livenessProbe:
          exec:
            command:
            - sh
            - health.sh
          initialDelaySeconds: 5
          periodSeconds: 1
  selector:
    matchLabels:
      app: ftps